/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import javax.swing.JOptionPane;
import logica.LOrdenar;

/**
 *
 * @author maria
 */
public class Principal extends javax.swing.JPanel {

    /**
     * Creates new form Principal
     */
    public Principal(LOrdenar lordenar) {
        initComponents();
        this.lordenar = lordenar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lista = new javax.swing.JComboBox<>();
        crear = new javax.swing.JButton();
        area = new java.awt.TextArea();

        lista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir tamaño", "10.000", "100.000", "1.000.000" }));

        crear.setText("Crear lista");
        crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(lista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(crear)
                .addContainerGap(185, Short.MAX_VALUE))
            .addComponent(area, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(area, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
        String seleccion = (String) lista.getSelectedItem();
        switch(seleccion){
            case "10.000":  lordenar.setDiezMil(lordenar.crear(10000));
                            area.setText(lordenar.concatenar(lordenar.getDiezMil()));
                break;
            case "100.000": lordenar.setCienMil(lordenar.crear(100000));
                            area.setText(lordenar.concatenar(lordenar.getCienMil()));
                break;
            case "1.000.000":   lordenar.setUnMillon(lordenar.crear(1000000));
                                area.setText(lordenar.concatenar(lordenar.getUnMillon()));
                break;
            default:    JOptionPane.showMessageDialog(null, "Selecciona una lista a generar", null, JOptionPane.INFORMATION_MESSAGE);
                break;
        }
    }//GEN-LAST:event_crearActionPerformed

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextArea area;
    private javax.swing.JButton crear;
    private javax.swing.JComboBox<String> lista;
    // End of variables declaration//GEN-END:variables
    private LOrdenar lordenar;



}
