/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.util.ArrayList;
import javax.swing.JMenuBar;
import javax.swing.JOptionPane;
import logica.LOrdenar;

/**
 *
 * @author maria
 */
public class QuickSort extends javax.swing.JPanel {

    /**
     * Creates new form QuickSort
     */
    public QuickSort(LOrdenar lordenar) {
        initComponents();
        this.lordenar = lordenar;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        ordenar = new java.awt.Button();
        lista = new javax.swing.JComboBox<>();
        label1 = new java.awt.Label();
        area = new java.awt.TextArea();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("jMenu3");

        setPreferredSize(new java.awt.Dimension(659, 475));

        ordenar.setLabel("Ver lista ordenada");
        ordenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordenarActionPerformed(evt);
            }
        });

        lista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ejecuciones", "10.000", "100.000", "1.000.000" }));
        lista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaActionPerformed(evt);
            }
        });

        label1.setText("QUICKSORT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(area, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(lista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(ordenar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ordenar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(area, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ordenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordenarActionPerformed
        try{
            String seleccion = (String) lista.getSelectedItem();
            ArrayList<Integer> arrayList = new ArrayList<>();
            switch(seleccion){
                case "10.000":  arrayList = lordenar.getDiezMil();
                    break;
                case "100.000": arrayList = lordenar.getCienMil();
                    break;
                case "1.000.000":   arrayList = lordenar.getUnMillon();
                    break;
            }
            long tiempoInicial = System.nanoTime();
            lordenar.quickSort(arrayList, 0, arrayList.size() - 1);
            long tiempoFinal = System.nanoTime();
            area.setText(lordenar.concatenar(arrayList));
            tiempo(seleccion, tiempoFinal - tiempoInicial);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Selecciona una lista existente a ordenar", null, JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_ordenarActionPerformed

    private void tiempo(String seleccion, long tiempo){
        switch(seleccion){
            case "10.000":  lordenar.getOrdenar().setTiempoQ(0, tiempo);
                break;
            case "100.000": lordenar.getOrdenar().setTiempoQ(1, tiempo);
                break;
            case "1.000.000":   lordenar.getOrdenar().setTiempoQ(2, tiempo);
                break;
        }
    }
    
    private void listaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaActionPerformed
        
    }//GEN-LAST:event_listaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextArea area;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private java.awt.Label label1;
    private javax.swing.JComboBox<String> lista;
    private java.awt.Button ordenar;
    // End of variables declaration//GEN-END:variables
    private LOrdenar lordenar;



}
