/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import logica.LOrdenar;

/**
 *
 * @author maria
 */
public class Tiempo extends javax.swing.JPanel {

    /**
     * Creates new form Primero
     */
    public Tiempo(LOrdenar lordenar) {
        initComponents();
        this.lordenar = lordenar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        calcular = new javax.swing.JButton();
        advertencia = new javax.swing.JLabel();

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ALGORITMO", "EJECUCION", "TIEMPO/nano seg"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Long.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);

        calcular.setText("Calcular tiempos");
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(advertencia))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(calcular)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(calcular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(advertencia)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
        TableModel modelo = tabla.getModel();

        modelo.setValueAt("Burbuja", 0, 0);
        modelo.setValueAt(1, 0, 1);
        modelo.setValueAt(lordenar.getOrdenar().getTiempoB()[0], 0, 2);
        ///
        modelo.setValueAt("Burbuja", 1, 0);
        modelo.setValueAt(2, 1, 1);
        modelo.setValueAt(lordenar.getOrdenar().getTiempoB()[1], 1, 2);
        ///
        modelo.setValueAt("Burbuja", 2, 0);
        modelo.setValueAt(3, 2, 1);
        modelo.setValueAt(lordenar.getOrdenar().getTiempoB()[2], 2, 2);

        modelo.setValueAt("QuickSort", 3, 0);
        modelo.setValueAt(1, 3, 1);
        modelo.setValueAt(lordenar.getOrdenar().getTiempoQ()[0], 3, 2);
        ///
        modelo.setValueAt("QuickSort", 4, 0);
        modelo.setValueAt(2, 4, 1);
        modelo.setValueAt(lordenar.getOrdenar().getTiempoQ()[1], 4, 2);
        ///
        modelo.setValueAt("QuickSort", 5, 0);
        modelo.setValueAt(3, 5, 1);
        modelo.setValueAt(lordenar.getOrdenar().getTiempoQ()[2], 5, 2);
        
        modelo.setValueAt("Insercion", 6, 0);
        modelo.setValueAt(1, 6, 1);
        modelo.setValueAt(lordenar.getOrdenar().getTiempoC()[0], 6, 2);
        ///
        modelo.setValueAt("Insercion", 7, 0);
        modelo.setValueAt(2, 7, 1);
        modelo.setValueAt(lordenar.getOrdenar().getTiempoC()[1], 7, 2);
        ///
        modelo.setValueAt("Insercion", 8, 0);
        modelo.setValueAt(3, 8, 1);
        modelo.setValueAt(lordenar.getOrdenar().getTiempoC()[2], 8, 2);
        
        modelo.setValueAt("Merge", 9, 0);
        modelo.setValueAt(1, 9, 1);
        modelo.setValueAt(lordenar.getOrdenar().getTiempoD()[0], 9, 2);
        ///
        modelo.setValueAt("Merge", 10, 0);
        modelo.setValueAt(2, 10, 1);
        modelo.setValueAt(lordenar.getOrdenar().getTiempoD()[1], 10, 2);
        ///
        modelo.setValueAt("Merge", 11, 0);
        modelo.setValueAt(3, 11, 1);
        modelo.setValueAt(lordenar.getOrdenar().getTiempoD()[2], 11, 2);


        advertencia.setText("Si algun valor se encuentra en cero, verifica que ya hayas creado y organizado la lista");
    }//GEN-LAST:event_calcularActionPerformed

 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel advertencia;
    private javax.swing.JButton calcular;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
    private LOrdenar lordenar;



}
